Added translation for left stick for color radios
EdgeTX/edgetx pull request #2655
Opened 2022-10-30 19:37 UTC by ulfhedlund

Summary of changes:
Added translation for left stick (TR_LEFT_STICK), used in selection of mode for color radios.

NB! If the translation is more than five/six letters it might be too long to fit in the drop down menu for the NV14 radio.
In the SE translation file I've therefore added this, which makes it look OK but perhaps is a bit crude:
#if defined(PCBNV14)
  #define TR_LEFT_STICK "Vä"
#else
  #define TR_LEFT_STICK "Vänster"
#endif

I have added google translations for several languages but they obviously need to be checked by the translators. If they provide the proper translations to me I'll add them in the translation files.

2022-10-30 19:43 UTC, ulfhedlund commented
Hello translators! 
If you can please provide the proper translation for left (as in left stick, used for mode selection) I can add them to the translation files before merge.
### 
@ParkerEde / @TheIsotopes DE
@Eldenroot CZ
@zyren CN / TW
@HThuren DA
@robustini IT

2022-10-30 20:15 UTC, Eldenroot commented
Hi, you are right and you have already added the translation for the Czech pack :)

`#define TR_LEFT_STICK                  "Vlevo"`

2022-10-30 20:16 UTC, Eldenroot commented
Btw we do not need "RIGHT"? :)

2022-10-30 21:13 UTC, ulfhedlund commented
Not for the mode selection, I believe.Den 30 okt. 2022 21:16 skrev Eldenroot ***@***.***>:
Btw we do not need "RIGHT"? :)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-30 22:38 UTC, HThuren commented
#if defined(PCBNV14)
#define TR_LEFT_STICK "Ven"
#else
#define TR_LEFT_STICK "Venstre"
#endif

2022-10-31 06:11 UTC, zyren commented
CN
**********************************************************
#if defined(PCBNV14)
#define TR_LEFT_STICK "左摇杆"
#else
#define TR_LEFT_STICK "左摇杆"
#endif
**********************************************************

TW
**********************************************************
#if defined(PCBNV14)
#define TR_LEFT_STICK "左搖桿"
#else
#define TR_LEFT_STICK "左搖桿"
#endif
**********************************************************

2022-10-31 07:14 UTC, TheIsotopes commented
Here `DE` translation

```
#if defined(PCBNV14)
#define TR_LEFT_STICK "Li"
#else
#define TR_LEFT_STICK "Links"
#endif
```

2022-10-31 07:18 UTC, robustini commented
#if defined(PCBNV14)
#define TR_LEFT_STICK "Sx"
#else
#define TR_LEFT_STICK "Sinistro"
#endif

2022-10-31 09:02 UTC, pfeerick requested changes
Looking good, just some minor changes please ;)

2022-10-31 15:33 UTC, ulfhedlund commented on radio/src/translations/se.h
> +#if defined(PCBNV14)
Yes, sorry forgot about that - will change to LDC_W > LCD_H. 
In this case the TR3 macro can't be used for NV14. The medium screen width seems to be for X9D-type displays only and for NV14 the wide screen is used.

2022-10-31 16:53 UTC, ulfhedlund commented
@pfeerick - I've now made the changes you suggested and added the translations provided. Lets see what the translators say but unless I've made some mistake this PR is ready for merge, at your discretion.

2022-10-31 18:49 UTC, ParkerEde commented
> Hello again translators! Please verify that I have added your translations correctly.
> 
> @ParkerEde / @TheIsotopes DE @Eldenroot CZ @zyren CN / TW @HThuren DA @robustini IT

DE
okay

2022-10-31 21:01 UTC, Eldenroot commented
CZ :OK

2022-10-31 21:49 UTC, HThuren commented
DA: ok

2022-10-31 23:25 UTC, pfeerick commented on radio/src/translations/se.h
> +#if defined(PCBNV14)
Ah, yes, damnit... the NV14 falls through the cracks there. The way you did it is then :)

2022-10-31 23:29 UTC, pfeerick approved these changes
LGTM... I'll give it a little more time to allow for replies and merge nearer to nightly.

2022-11-01 02:01 UTC, merged