chore(color) - LVGL update and translation strings for theme file carousel.
EdgeTX/edgetx pull request #3278
Opened 2023-02-28 03:21 UTC by philmoz

Use StaticText instead of 'paint' function for 'loading' message in theme file carousel.
Add message strings to translation files.

2023-02-28 23:42 UTC, pfeerick commented
Can we get some translations for this please 😃 

![image](https://user-images.githubusercontent.com/5500713/222008313-3fadf001-ae9a-42fe-8d50-609c56707675.png)


```
#define TR_NO_THEME_IMAGE "No theme image"
```

- [ ] @HThuren DA
- [ ] @ParkerEde / @TheIsotopes DE
- [ ] @Eldenroot CZ
- [ ] @ulfhedlund SE
- [ ] @robustini IT
- [ ] @zyren CN / TW
- [ ] @ajjjjjjjj PL
- [ ] @ToshihiroMakuuchi JP

2023-03-01 01:07 UTC, HThuren commented
DA
#define TR_EDIT_COLOR                  "Rediger farve"
#define TR_NO_THEME_IMAGE              "Ingen billede for tema"

2023-03-01 06:50 UTC, robustini commented
IT
#define TR_EDIT_COLOR           "Edita colore"
#define TR_NO_THEME_IMAGE "Nessuna\nimmagine\ntrovata"

I hope there are three lines available.
Italian is a wonderful language but it is difficult to abbreviate words.

2023-03-01 07:00 UTC, philmoz commented
> #define TR_NO_THEME_IMAGE "Nessuna\nimmagine\ntrovata"
> 
> I hope there are three lines available. Italian is a wonderful language but it is difficult to abbreviate words.

Thanks, forced newlines are not necessary. The text will wrap as needed.

2023-03-01 07:15 UTC, ulfhedlund commented
SE: #define TR_NO_THEME_IMAGE "Ingen temabild"Den 1 mars 2023 00:42 skrev Peter Feerick ***@***.***>:

Can we get some translations for this please 😃



#define TR_NO_THEME_IMAGE "No theme image"



 @HThuren DA @ParkerEde / @TheIsotopes DE @Eldenroot CZ @ulfhedlund SE @robustini IT @zyren CN / TW @ajjjjjjjj PL @ToshihiroMakuuchi JP



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-01 07:51 UTC, TheIsotopes commented
DE

```
#define TR_EDIT_COLOR                  "Farbe bearbeiten"
#define TR_NO_THEME_IMAGE              "Kein Theme Bild"
```

2023-03-01 21:07 UTC, Eldenroot requested changes

2023-03-01 21:07 UTC, Eldenroot commented on radio/src/translations/cz.h
>  #define TR_EDIT_COLOR                  "Edit Color"
Změnit barvu

2023-03-01 21:07 UTC, Eldenroot commented on radio/src/translations/cz.h
> +#define TR_NO_THEME_IMAGE              "No theme image"
Náhled motivu nedostupný

2023-03-01 21:09 UTC, Eldenroot commented
CZ commented

2023-03-04 05:45 UTC, ToshihiroMakuuchi commented
JP
#define TR_EDIT_COLOR "カラー編集"
#define TR_NO_THEME_IMAGE "テーマ画像はありません"

2023-03-05 17:17 UTC, zyren commented
********************************************************
CN

#define TR_EDIT_COLOR "编辑颜色"
#define TR_NO_THEME_IMAGE "没有预览图"
*********************************************************
*********************************************************
TW

#define TR_EDIT_COLOR "編輯顏色"
#define TR_NO_THEME_IMAGE "沒有預覽圖"
*********************************************************

2023-03-06 19:08 UTC, Eldenroot commented
CZ: "Upravit barvu"

This fits better

@philmoz

2023-03-07 01:58 UTC, merged