Automatically extract CN and TW characters from the translation file.
EdgeTX/edgetx pull request #3650
Opened 2023-06-03 01:33 UTC by zyren

I created get_cn_char.py and get_tw_char.py to extract all Chinese characters from the translation file. I modified make_fonts.sh to import the extraction results, making it very easy to generate the font library.

2023-06-04 11:46 UTC, arthurson commented
any chance to change font to more readible?
now it is hard to read the chinese.

2023-06-04 22:34 UTC, zyren commented
> 

May I ask if the Chinese expressions are hard to understand, or the font is not pleasing? If some translations are inaccurate, please correct them. You can list some confusing contents, and I will do my best to check and modify to achieve the best.

2023-06-07 03:11 UTC, richardclli commented
Let me take a look.

2023-06-07 17:02 UTC, arthurson commented
i mean the font now it uses is not clear to read, not related to translations that you made.

2023-08-12 05:54 UTC, raphaelcoeffic commented on radio/src/fonts/lvgl/get_cn_char.py
> +                if '\u4e00' <= char <= '\u9fff':
Please define a "constant" for these, so we know what they correspond to.

2023-08-12 05:55 UTC, raphaelcoeffic requested changes
It seems these 2 files are more or less copy of one another. Can we have a consolidated version using parameters so that difference can be worked out?

2023-10-14 02:25 UTC, richardclli commented
Replaced by https://github.com/EdgeTX/edgetx/pull/4202

2023-10-14 02:25 UTC, closed without merging